server:
  port: 30001

spring:
  application:
    name: orangelala-service-inventory
  datasource:
    url: jdbc:mysql://localhost:3306/orangelala_inventory?useSSL=false&serverTimezone=UT
    username: root
    password: root
  cloud:
    alibaba:
      seata:
        tx-service-group: my_order_tx_group
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mapper/**.xml
inventory: 
  list: 
    size: 20   #存放队列的数量
  pool: 
    size: 20   #处理业务的线程数量
  queue:
    size: 100  #每个队列的大小
  query_time_out: 20000   #查询超时时间(毫秒)
  await_update_timeout: 20  #等待更新结果超时时间
  zkNodes: 139.155.113.168:2181           #zookeeper节点
  zkConnectTimeout: 8000  #获取锁的时间限制
  
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:10000/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: orangelala-service-inventory-30001 #指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
  
logging:
  level: 
    org: 
      springframework: 
        cloud: 
          alibaba: 
            seata: 
              web: debug
  io: 
    seata: debug